services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/totem
      - JWT_SECRET=a_very_secret_key_that_should_be_in_a_secret_manager
      - OTLP_ENDPOINT=jaeger:4317
      - SERVICE_NAME=totem-api
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - APP_ENV=development
      - CORS_ORIGINS=http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:3000
      - MERCADOPAGO_ACCESS_TOKEN=APP_USR-4562501449641015-072916-9885265dc729abd0dc3f8683e25ce47b-2587380047
      - MERCADOPAGO_PUBLIC_KEY=APP_USR-16377f98-47c0-412f-98c8-6e87dff2690b
      - MERCADOPAGO_WEBHOOK_URL=https://b3c5ada464b8.ngrok-free.app/webhooks/mercadopago
    depends_on:
      db:
        condition: service_healthy
      jaeger:
        condition: service_started         # opcional
    networks:
      - totem-network
    command: >
      sh -c "
        until pg_isready -h db -U postgres ; do echo 'Aguardando DB...' && sleep 2 ; done &&
        uvicorn apps.api.full_api:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=totem
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - totem-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  jaeger:
    image: jaegertracing/all-in-one:1.46
    ports:
      - "16686:16686"  # UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - totem-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:16686/api/services"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prom_configs:/etc/prometheus:ro
      - prometheus_data:/prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    networks:
      - totem-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager_config:/etc/alertmanager:ro
      - alertmanager_data:/alertmanager
    command: ["--config.file=/etc/alertmanager/alertmanager.yml"]
    environment:
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    networks:
      - totem-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  node-exporter:
    image: prom/node-exporter:v1.6.1
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - totem-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - totem-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  panel:
    build:
      context: .
      dockerfile: apps/panel-client/Dockerfile
    depends_on: [api]
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000/ws
      - VITE_TENANT_ID=7f02a566-2406-436d-b10d-90ecddd3fe2d
    ports:
      - "5175:80"          # porta externa → porta nginx
    networks: [totem-network]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3

  totem:
    build:
      context: .
      dockerfile: apps/totem-client/Dockerfile
    depends_on: [api]
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_TENANT_ID=7f02a566-2406-436d-b10d-90ecddd3fe2d
      - VITE_WS_URL=ws://localhost:8000/ws
      - VITE_MOCK_PAYMENT=true
    ports:
      - "5174:80"
    networks: [totem-network]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  prometheus_data:
  alertmanager_data:
  grafana_data:

networks:
  totem-network:
    driver: bridge

configs:
  prometheus_cfg:
    file: ./prom_configs/prometheus.yml
  prometheus_rules:
    file: ./prom_configs/alert.rules
  alert_cfg:
    file: ./alertmanager_config/alertmanager.yml 