"""add ticket_id to payment_sessions

Revision ID: 016
Revises: 
Create Date: 2025-07-30 05:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_sessions', sa.Column('ticket_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'payment_sessions', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_sessions', type_='foreignkey')
    op.drop_column('payment_sessions', 'ticket_id')
    # ### end Alembic commands ### 