"""make payment_session_id nullable in tickets

Revision ID: 019
Revises: 018
Create Date: 2025-08-06 21:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '019'
down_revision = '018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'payment_session_id',
               existing_type=postgresql.UUID(as_uuid=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'payment_session_id',
               existing_type=postgresql.UUID(as_uuid=True),
               nullable=False)
    # ### end Alembic commands ### 